apiVersion: apps/v1
kind: Deployment
metadata:
  name: loss
  labels:
    app: loss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loss
  template:
    metadata:
      labels:
        app: loss
    spec:
      containers:
        - name: loss
          image: "username/loss:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
