server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: phone
          uri: http://localhost:8082
          predicates:
            - Path=/phoneManagements/**, 
        - id: loss
          uri: http://localhost:8083
          predicates:
            - Path=/lossManagements/**, 
        - id: alarm
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: user
          uri: http://localhost:8085
          predicates:
            - Path=/userManagements/**, 
        - id: report
          uri: http://localhost:8086
          predicates:
            - Path=/reportManagements/**, 
        - id: rental
          uri: http://localhost:8087
          predicates:
            - Path=/rentalManagements/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: phone
          uri: http://phone:8080
          predicates:
            - Path=/phoneManagements/**, 
        - id: loss
          uri: http://loss:8080
          predicates:
            - Path=/lossManagements/**, 
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path=, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/userManagements/**, 
        - id: report
          uri: http://report:8080
          predicates:
            - Path=/reportManagements/**, 
        - id: rental
          uri: http://rental:8080
          predicates:
            - Path=/rentalManagements/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
